all:
  vars:
    # For this to work, run the `RUN_BOOTSTRAP` script first
    ansible_user: ansible-sudo-user

  children:
    k8s-masters:
      hosts:
        k8s-master1:

    k8s-workers:
      hosts:
        k8s-worker1:
        k8s-worker2:

    k8s:
      children:
        k8s-masters:
        k8s-workers:

    monitoring:
      hosts:
        prometheus-grafana-server:
