#!/bin/bash

# Define the cron jobs you want to add
reboot_lxc="0 0,12 * * * $(pwd)/lxc-reboot.sh 101"

function add_cron_job(){
    job=$1
    # Check if the cron job already exists
    crontab -l | grep -F "$job" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
    echo "Cron job already exists. No changes made."
    else
    # Add the cron job
    (crontab -l 2>/dev/null; echo "$job") | crontab -
    echo "Cron job added successfully."
    fi
}

# Append to crontab your jobs
add_cron_job "${reboot_lxc}"
