apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  # FIXME: Make this more rubust
  hostPath:
    path: /data/frigate/config
