apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: applications # TODO: Check if this is the proper ns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: frigate-config-pv
