apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data
  namespace: applications # TODO: Check if this is the proper ns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  volumeName: frigate-data-pv
