apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: frigate-config-pv
