apiVersion: v1
kind: Service
metadata:
  labels:
    app: frigate
  name: frigate
  namespace: applications # TODO: Check if this is the proper ns
spec:
  ports:
  # HTTP
  # - name: http
  #   port: 5000
  #   protocol: TCP
  #   targetPort: 5000
  #   nodePort: 30432
  # TLS
  - name: https
    port: 8971
    protocol: TCP
    targetPort: 8971
    nodePort: 30435
  selector:
    app: frigate
  type: NodePort
status:
  loadBalancer: {}
