apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace name, prefix and app label for all resources come from here
namespace: privileged-apps
namePrefix: privileged-apps-

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: privileged-apps    # TODO: change also this in any future ones

resources:
  - namespace.yaml
  - limitrange.yaml
  - resourcequota.yaml
