apiVersion: v1
kind: LimitRange
metadata:
  name: lr
spec:
  limits:
  # ========================================
  # Container
  # ========================================
  - type: Container
    defaultRequest:     # this section defines default requests
      cpu: "50m"
      memory: "50Mi"
    default:          # this section defines default limits
      cpu: 500m
      memory: "100Mi"

  # ========================================
  # Pod
  # ========================================
  - type: Pod
    max: 
      cpu: "4"
      memory: "6Gi"
