apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq
spec:
  hard:
    # Mem/CPU
    requests.cpu: "3"
    requests.memory: "3.5Gi"
    limits.cpu: "6"
    limits.memory: "8Gi"
    
    # Pods
    pods: "10"

    # Resources
    persistentvolumeclaims: "4"
    secrets: "10"
    configmaps: "10"
    services: "10"