# ====================================================================
# Dependencies
# ====================================================================

- name: Ensure dependencies are installed
  ansible.builtin.package:
    update_cache: yes
    state: present
    name:  
      - curl

# ====================================================================
# Disable swap
# ====================================================================

- name: Disable swap if active
  ansible.builtin.shell: "swapoff -a"
  when: ansible_swaptotal_mb > 0
  become: true

- name: Comment out /swap line in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(/swap.*)'
    replace: '#\1'
    backup: yes
  become: true

# - name: Ensure swap is disabled
#   ansible.builtin.shell: "free | grep -i swap | awk '{print $2}'"
#   register: swap_check
#   changed_when: false

# - name: Fail if swap is still enabled
#   ansible.builtin.fail:
#     msg: "Swap is still enabled!"
#   when: swap_check.stdout|int > 01

# ====================================================================
# Install and setup containerd
# ====================================================================

- name: Install containerd
  ansible.builtin.package:
    name: containerd
    state: present
    update_cache: yes

- name: Create /etc/containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: Generate default containerd config to temporary file
  ansible.builtin.command: containerd config default
  register: containerd_config

- name: Save containerd config to /etc/containerd/config.toml
  ansible.builtin.copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'

- name: Enable Systemd Cgroup in containerd config
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)SystemdCgroup\s*=\s*false'
    replace: '\1SystemdCgroup = true'
  become: true

- name: Restart and enable containerd
  systemd:
    name: containerd
    enabled: yes
    state: restarted

# ====================================================================
# Install and setup kubeadm, kubelet and kubectl
# see: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
# ====================================================================

- name: Ensure dependencies are installed
  ansible.builtin.package:
    update_cache: yes
    state: present
    name:
      - apt-transport-https 
      - ca-certificates 
      - curl
      - gpg

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    mode: '0755'

- name: Download Kubernetes Release key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key"
    dest: /tmp/kubernetes-Release.key

- name: Add Kubernetes Release key to apt keyring
  ansible.builtin.apt_key:
    file: /tmp/kubernetes-Release.key
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /
    state: present
    filename: kubernetes

- name: Install Kubernetes components
  ansible.builtin.package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  ansible.builtin.command: "apt-mark hold {{ item }}"
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: true

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: true

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

# ====================================================================
# Enable IP forwarding
# ====================================================================

- name: Enable IP forwarding temporarily
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Ensure IP forwarding is enabled permanently
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward = 1'
    create: yes
    state: present

- name: Apply sysctl settings
  ansible.builtin.command: sysctl -p