apiVersion: v1
kind: Service
metadata:
  name: ittools
spec:
  type: NodePort  # TODO: remove this after proxy addition
  selector:
    app.kubernetes.io/name: ittools
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30020 # TODO: remove this after proxy addition
