---
# ====================================================================
# All nodes (Debian & Redhat, if exist any)
# ====================================================================
- name: Apply base configuration to all hosts
  hosts: all
  become: true
  roles:
    - base

# ====================================================================
# Prometheus and Grafana server
# ====================================================================
- name: Configure monitoring server
  hosts: prometheus-grafana-server
  become: true
  tasks:
    - name: Include prometheus-server role
      include_role:
        name: prometheus-server
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Include grafana-server role
      include_role:
        name: grafana-server
      when: ansible_distribution in ["Ubuntu", "Debian"]