---
# ====================================================================
# All nodes (Debian & Redhat, if exist any)
# ====================================================================
- name: Apply base configuration to all hosts
  hosts: all
  become: true
  roles:
    - base

# ====================================================================
# All K8s nodes (workers + masters)
# ====================================================================
- name: Configure Kubernetes nodes (control plane + workers)
  hosts: k8s
  become: true
  tasks:
    - name: Include k8s-node role
      include_role:
        name: k8s-node
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Include prometheus-agent role
      include_role:
        name: prometheus-agent
      when: ansible_distribution in ["Ubuntu", "Debian"]

# ====================================================================
# Only K8s master nodes
# ====================================================================
- name: Configure Kubernetes master nodes
  hosts: k8s-masters[0]
  become: true
  tasks:
    - name: Include k8s-master role
      include_role:
        name: k8s-master
      when: ansible_distribution in ["Ubuntu", "Debian"]

# ====================================================================
# Only K8s worker nodes
# ====================================================================
- name: Configure Kubernetes worker nodes
  hosts: k8s-workers
  become: true
  tasks:
    - name: Include k8s-worker role
      include_role:
        name: k8s-worker
      when: ansible_distribution in ["Ubuntu", "Debian"]

# ====================================================================
# Prometheus and Grafana server
# ====================================================================
- name: Configure monitoring server
  hosts: prometheus-grafana-server
  become: true
  tasks:
    - name: Include prometheus-server role
      include_role:
        name: prometheus-server
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Include grafana-server role
      include_role:
        name: grafana-server
      when: ansible_distribution in ["Ubuntu", "Debian"]